import { isTextBlock, type NativeChatMessage } from '../../../../shared/native-chat-types'

// Why: the harness injects machinery into the agent's conversation as user-role
// turns — background task-notifications, system reminders, local-command output,
// slash-command envelopes, interruption/compaction notices. These land in the
// transcript but are not real user messages, so the chat filters them out (they
// were confusingly rendered as the user's own bubbles). Mirrors the mobile
// predicate in mobile/src/session/mobile-native-chat-noise.ts.

const NOISE_PREFIXES = [
  '<task-notification>',
  '<system-reminder>',
  '<local-command-stdout>',
  '<local-command-caveat>',
  '<command-name>',
  '<command-message>',
  '<command-args>',
  '<bash-',
  '[request interrupted',
  'caveat: the messages below were generated by the user while running local commands',
  'this session is being continued from a previous conversation'
]

function messageText(message: NativeChatMessage): string {
  return message.blocks
    .filter(isTextBlock)
    .map((b) => b.text)
    .join('')
    .trim()
}

/** True when a message is harness machinery rather than real conversation. Only
 *  user/system turns qualify — assistant/tool turns and any turn carrying real
 *  tool activity are always kept. */
export function isNoiseMessage(message: NativeChatMessage): boolean {
  if (message.role !== 'user' && message.role !== 'system') {
    return false
  }
  // Keep turns that carry tool activity (e.g. a user turn with tool results).
  if (message.blocks.some((b) => b.type === 'tool-call' || b.type === 'tool-result')) {
    return false
  }
  const text = messageText(message).toLowerCase()
  if (text.length === 0) {
    return false
  }
  return NOISE_PREFIXES.some((prefix) => text.startsWith(prefix))
}

/** Drop harness-noise messages from a transcript. */
export function stripNoiseMessages(messages: readonly NativeChatMessage[]): NativeChatMessage[] {
  return messages.filter((m) => !isNoiseMessage(m))
}
